management:
  endpoints:
    web:
      exposure:
        include: "*"
app:
  data:
    default data from application yaml
spring:
  cache:
    type: hazelcast
  kafka:
    bootstrap-servers: my-cluster-kafka-bootstrap.kafka:9092
