hazelcast:
  enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
app:
  data:
    default data from application yaml
spring:
  kafka:
    bootstrap-servers: my-cluster-kafka-bootstrap.kafka:9092

logging:
  level:
    com:
      hazelcast:
        system:
          logo: OFF
